apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-discoverer-binding
  namespace: library-helm
subjects:
  - kind: ServiceAccount
    name: admin
    apiGroup: ""
roleRef:
  apiGroup: ""
  kind: Role
  name: admin-discoverer
