apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin.fullname" . }}-secrets
  labels:
    {{- include "admin.labels" . | nindent 4 }}
data:
  ACTUATOR_USERNAME: "YWRtaW4="  # admin
  ACTUATOR_PASSWORD: "c2VjcmV0" # secret
  SECURITY_USERNAME: "cm9vdA==" # root
  SECURITY_PASSWORD: "cGFzc3dvcmQ=" # password