apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin.fullname" . }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
    tech-stack: springboot
spec:
  selector:
    app: {{- include "admin.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  type: ClusterIP