spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            admin:
              - uri: ${ADMIN_HOST:http://localhost}:${server.port}
                metadata:
                  management.context-path: ${management.endpoints.web.base-path}
            application:
              - uri: ${APPLICATION_HOST:http://localhost}:${monitored.application.port}
                metadata:
                  management.context-path: ${monitored.application.actuator-endpoint}

monitored:
  application:
    port: 8080
    actuator-endpoint: /admin