apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
  namespace: library
data:
  ACTUATOR_USERNAME: "YWRtaW4="  # admin
  ACTUATOR_PASSWORD: "c2VjcmV0" # secret
  SECURITY_USERNAME: "cm9vdA==" # root
  SECURITY_PASSWORD: "cGFzc3dvcmQ=" # password